/*
* ============================================================================
*  Name     : CSmscDocument from SmscDocument.h
*  Part of  : Smsc
*  Created  : 30/7/2003 by Makidis Michael
*  Implementation notes:
*     This class is just a placeholder.
*     Initial content was generated by Series 60 AppWizard.
*  Copyright: Makidis Michael 2003-2004
* ============================================================================
*/

// INCLUDE FILES
#include "SmscDocument.h"
#include "SmscAppUi.h"

// ================= MEMBER FUNCTIONS =======================

// constructor
CSmscDocument::CSmscDocument(CEikApplication& aApp)
: CAknDocument(aApp)    
    {
    }

// destructor
CSmscDocument::~CSmscDocument()
    {
    }

// EPOC default constructor can leave.
void CSmscDocument::ConstructL()
    {
    }

// Two-phased constructor.
CSmscDocument* CSmscDocument::NewL(
        CEikApplication& aApp)     // CSmscApp reference
    {
    CSmscDocument* self = new (ELeave) CSmscDocument( aApp );
    CleanupStack::PushL( self );
    self->ConstructL();
    CleanupStack::Pop();

    return self;
    }
    
// ----------------------------------------------------
// CSmscDocument::CreateAppUiL()
// constructs CSmscAppUi
// ----------------------------------------------------
//
CEikAppUi* CSmscDocument::CreateAppUiL()
    {
    return new (ELeave) CSmscAppUi;
    }

// End of File  
