/*
* ============================================================================
*  Name     : CSmscApp from SmscApp.cpp
*  Part of  : Smsc
*  Created  : 30/7/2003 by Makidis Michael
*  Implementation notes:
*     Initial content was generated by Series 60 AppWizard.
*  Copyright: Makidis Michael 2003-2004
* ============================================================================
*/

// INCLUDE FILES
#include    "SmscApp.h"
#include    "SmscDocument.h"

// ================= MEMBER FUNCTIONS =======================

// ---------------------------------------------------------
// CSmscApp::AppDllUid()
// Returns application UID
// ---------------------------------------------------------
//
TUid CSmscApp::AppDllUid() const
    {
    return KUidSmsc;
    }

   
// ---------------------------------------------------------
// CSmscApp::CreateDocumentL()
// Creates CSmscDocument object
// ---------------------------------------------------------
//
CApaDocument* CSmscApp::CreateDocumentL()
    {
    return CSmscDocument::NewL( *this );
    }

// ================= OTHER EXPORTED FUNCTIONS ==============
//
// ---------------------------------------------------------
// NewApplication() 
// Constructs CSmscApp
// Returns: created application object
// ---------------------------------------------------------
//
EXPORT_C CApaApplication* NewApplication()
    {
    return new CSmscApp;
    }

// ---------------------------------------------------------
// E32Dll(TDllReason) 
// Entry point function for EPOC Apps
// Returns: KErrNone: No error
// ---------------------------------------------------------
//
GLDEF_C TInt E32Dll( TDllReason )
    {
    return KErrNone;
    }

// End of File  

