/*
* ============================================================================
*  Name     : CSmscView2 from SmscView2.h
*  Part of  : Smsc
*  Created  : 30/7/2003 by Makidis Michael
*  Implementation notes:
*     Initial content was generated by Series 60 AppWizard.
*  Copyright: Makidis Michael 2003-2004
* ============================================================================
*/

// INCLUDE FILES
#include  "SmscView2.h"
#include  "SmscContainer2.h"
#include  "Smsc.hrh"
#include  <Smsc.rsg>
#include  <aknviewappui.h>
#include  <avkon.hrh>

// ================= MEMBER FUNCTIONS =======================

// ---------------------------------------------------------
// CSmscView2::ConstructL(const TRect& aRect)
// EPOC two-phased constructor
// ---------------------------------------------------------
//
void CSmscView2::ConstructL()
    {
    BaseConstructL( R_SMSC_VIEW2 );
    }

// ---------------------------------------------------------
// CSmscView2::~CSmscView2()
// ?implementation_description
// ---------------------------------------------------------
//
CSmscView2::~CSmscView2()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }

    delete iContainer;
    }

// ---------------------------------------------------------
// TUid CSmscView2::Id()
// ?implementation_description
// ---------------------------------------------------------
//
TUid CSmscView2::Id() const
    {
    return KView2Id;
    }

// ---------------------------------------------------------
// CSmscView2::HandleCommandL(TInt aCommand)
// ?implementation_description
// ---------------------------------------------------------
//
void CSmscView2::HandleCommandL(TInt aCommand)
    {   
    AppUi()->HandleCommandL( aCommand );
    }

// ---------------------------------------------------------
// CSmscView2::HandleClientRectChange()
// ---------------------------------------------------------
//
void CSmscView2::HandleClientRectChange()
    {
    if ( iContainer )
        {
        iContainer->SetRect( ClientRect() );
        }
    }

// ---------------------------------------------------------
// CSmscView2::DoActivateL(...)
// ?implementation_description
// ---------------------------------------------------------
//
void CSmscView2::DoActivateL(
   const TVwsViewId& /*aPrevViewId*/,TUid /*aCustomMessageId*/,
   const TDesC8& /*aCustomMessage*/)
    {
    if (!iContainer)
        {
        iContainer = new (ELeave) CSmscContainer2;
        iContainer->SetMopParent(this);
        iContainer->ConstructL( ClientRect() );
        AppUi()->AddToStackL( *this, iContainer );
        }
   }

// ---------------------------------------------------------
// CSmscView2::HandleCommandL(TInt aCommand)
// ?implementation_description
// ---------------------------------------------------------
//
void CSmscView2::DoDeactivate()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }
    
    delete iContainer;
    iContainer = NULL;
    }

// End of File

